version: '3.8'

networks:
  ci_network:
    driver: bridge

volumes:
  jenkins_home:
    external: true
  shared_output:        # ← este es el volumen que van a compartir todos los jobs

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins_server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - shared_output:/shared_output
    networks:
      - ci_network
    restart: unless-stopped

  python-runner:
    image: python:3.12-slim
    working_dir: /app/GSIT_Alertas/01-Email_Listener
    volumes:
      - .:/app/GSIT_Alertas/01-Email_Listener
      - ../..:/app
      - shared_output:/shared_output
      - ./01-Email_Listener/.env:/app/GSIT_Alertas/01-Email_Listener/.env:ro
    environment:
      - PYTHONUNBUFFERED=1
      - WORKSPACE=/shared_output
    networks:
      - ci_network

  selenium-firefox:
    build: ./selenium_runner
    container_name: selenium_runner
    volumes:
      - .:/app/GSIT_Alertas/01-Email_Listener
      - ../..:/app
      - shared_output:/shared_output
      - ./selenium_runner/certificado.p12:/home/seluser/certificado.p12:ro
    environment:
      - WORKSPACE=/shared_output
    shm_size: "2gb"
    networks:
      - ci_network
    restart: unless-stopped