FROM jenkins/jenkins:lts-jdk17

USER root

# INSTALAR PYTHON + PIP + VENV (para que el job 01 funcione)
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/* \
    && ln -s /usr/bin/python3 /usr/bin/python

USER jenkins
