FROM jenkins/jenkins:lts

USER root

# Pré-requisitos do Selenium com Firefox + XVFB
RUN apt-get update && apt-get install -y \
    python3 python3-venv python3-pip \
    firefox-esr \
    xvfb \
    xauth \
    wget unzip \
    && rm -rf /var/lib/apt/lists/*

# Instala Geckodriver oficial
RUN GECKO_VERSION=$(wget -qO- https://api.github.com/repos/mozilla/geckodriver/releases/latest \
    | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/') \
    && wget -q "https://github.com/mozilla/geckodriver/releases/download/v$GECKO_VERSION/geckodriver-v$GECKO_VERSION-linux64.tar.gz" \
    && tar -xzf geckodriver-v$GECKO_VERSION-linux64.tar.gz \
    && mv geckodriver /usr/local/bin/ \
    && chmod +x /usr/local/bin/geckodriver \
    && rm geckodriver-v$GECKO_VERSION-linux64.tar.gz

USER jenkins
